New Version of the code with dashboard frontend
CCS112Organization/Product-Management- pull request #10
Opened 2024-10-14 12:01 UTC by Siose-Patrick

2024-10-14 12:48 UTC, Saymo-Michael approved these changes
Nacheck ko na. Okay na

2024-10-14 13:06 UTC, Saymo-Michael approved these changes
wala pa naman akong nakitang mali.

2024-10-14 15:14 UTC, Sibayan-ShainahGrace requested changes
Mali yung spelling ng font-family name. Dapat "Montserrat," hindi "Monsterrat."

2024-10-14 15:14 UTC, Sibayan-ShainahGrace commented on react-webapp/src/App.css
There's a typo in the font-family name. It should be 'Montserrat' instead of 'Monsterrat.'

2024-10-15 02:37 UTC, Siose-Patrick commented on react-webapp/src/App.css
Updated the pull request with the applied the revision

2024-10-15 04:28 UTC, kwinsiii23 approved these changes
okay na, nabago yun wrong spelling. Approved

2024-10-15 04:33 UTC, Saymo-Michael approved these changes

2024-10-15 04:35 UTC, Saymo-Michael approved these changes
sorry di ko nakita i approve ko nato

2024-10-15 05:59 UTC, Sibayan-ShainahGrace approved these changes
okay na

2024-10-15 06:01 UTC, Saymo-Michael reviewed
Merge ko na

2024-10-15 06:01 UTC, merged